name: motherlang
description: Create any esolang
version: 0.0.1
repository: https://github.com/ayush221b/motherlang

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
